//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelAccessSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessCards
    {
        public int CardId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string AccessLevel { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
